compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: ./config/deepspeed.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
gpu_ids: 5,7
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false