exp_name: controlnet
work_dir: "./tmp"
dataset:
  train:
    cache_dir: "/mnt/opensource/huggingface/data/fusing-fill50k"
    kwargs:
      batch_size: 6
      num_workers: 4
model:
  Tokenizer:
    type: "transformers.AutoTokenizer"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/mnt/opensource/huggingface/hub"
  TextEncoder:
    type: "transformers.CLIPTextModel"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/mnt/opensource/huggingface/hub"
  AutoencoderKL:
    type: "diffusers.AutoencoderKL"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/mnt/opensource/huggingface/hub"
  Unet:
    type: "diffusers.UNet2DConditionModel"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/mnt/opensource/huggingface/hub"
  NoiseScheduler:
    type: "diffusers.DDPMScheduler"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/mnt/opensource/huggingface/hub"
train:
  max_epoch: 100
  lr: 5e-6
  pretrained_checkpoint: null
  resume_from: null
optimizer:
  type: "AdamW"
  kwargs:
    betas: [0.9, 0.999]
    weight_decay: 0.01
    eps: 1e-8
gpu:
  enable: true
  devices: "0"
accelerate:
  enable: true
  kwargs:
    gradient_accumulation_steps: 1
vis:
  log_step_period: 0
  tensorboard_step_period: 1000
  visualzation_step_period: 2500
  save_checkpoint_epoch_period: 5
