exp_name: controlnet
work_dir: "./tmp"
data:
  train:
    target: "123"
    kwargs:
      root_dir: ""
      sample_list_file_path: ""
    dataloader_kwargs:
      batch_size: 1
      num_workers: 1
  val: null

model:
  Tokenizer:
    type: "transformers.AutoTokenizer"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/home/hejing/data/opensource/huggingface/hub"
  TextEncoder:
    type: "transformers.CLIPTextModel"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/home/hejing/data/opensource/huggingface/hub"
  AutoencoderKL:
    type: "diffusers.AutoencoderKL"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/home/hejing/data/opensource/huggingface/hub"
  Unet:
    type: "diffusers.UNet2DConditionModel"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/home/hejing/data/opensource/huggingface/hub"
  NoiseScheduler:
    type: "diffusers.DDPMScheduler"
    model_card_name: "runwayml/stable-diffusion-v1-5"
    kwargs:
      cache_dir: "/home/hejing/data/opensource/huggingface/hub"
train:
  max_epoch: 100
  lr: 5e-6
  pretrained_checkpoint: null
  resume_from: null
optimizer:
  type: "AdamW"
  kwargs:
    betas: [0.9, 0.999]
    weight_decay: 0.01
    eps: 1e-8
gpu:
  enable: true
  devices: "5"
accelerate:
  enable: true
  enable_deepspeed: false
  kwargs:
    gradient_accumulation_steps: 2
    mixed_precision: 'no'
vis:
  log_step_period: 0
  tensorboard_step_period: 1000
  visualzation_step_period: 2500
  save_checkpoint_epoch_period: 5
